name: BetterCinematics
main: me.marquez.bettercinematics.BetterCinematics
version: ${version}
api-version: ${minecraft.version}
author: DevMarquez
depend: [ProtocolLib]
commands:
  bcm:
    aliases: bc
    description: BetterCinematics's default commands